### PR TITLE
Update placeholder Native-X description and navigation

### PR DESCRIPTION
**Pull request by jwade1327**
Screen Shot 2023-04-04 at 8 43 20 AM
Screen Shot 2023-04-04 at 8 43 26 AM
Screen Shot 2023-04-04 at 8 43 37 AM

### CODE REVIEW

**Comment by jwade1327** [comment]
[amPulmonary Site Punch List](https://trello.com/c/91mbqY5r/420-ampulmonary-site-punch-list)

**Comment by jwade1327** [comment]
[amPulmonary Site Punch List](https://trello.com/c/91mbqY5r/420-ampulmonary-site-punch-list)

**Review by Shinsina — CHANGES_REQUESTED** [review]
This PR title doesn't really tell me what got done here. This looks like navigation adjustments and Native-X configuration changes but I can only assume that based on looking at the code changes, is that what happened here?

If so the PR title should likely reflect what got updated about the amPulmonary website and the description updated to include any additional info that doesn't fit into a title.

**Review by Shinsina — CHANGES_REQUESTED** [review]
This PR title doesn't really tell me what got done here. This looks like navigation adjustments and Native-X configuration changes but I can only assume that based on looking at the code changes, is that what happened here?

If so the PR title should likely reflect what got updated about the amPulmonary website and the description updated to include any additional info that doesn't fit into a title.

**Review by Shinsina — APPROVED** [review]

**Pull request merged**
