### PR TITLE
Add ‘og:image’ meta tag for social sharing

### PR DESCRIPTION
**Pull request by jwade1327**
Edit:
Homepage:
Screen Shot 2023-03-09 at 10 52 58 AM
Content Page:
Screen Shot 2023-03-09 at 10 53 58 AM

Not sure how to test this but from what I researched:
https://developers.facebook.com/docs/sharing/webmasters/images/
adding this tag will resize the image when sharing on social media

### CODE REVIEW

**Comment by jwade1327** [comment]
[SHM - client comments on social previews rendering properly](https://trello.com/c/oPD5bNpc/433-shm-client-comments-on-social-previews-rendering-properly)

**Review by Shinsina — CHANGES_REQUESTED** [review]
> Not sure how to test this but from what I researched: https://developers.facebook.com/docs/sharing/webmasters/images/ adding this tag will resize the image when sharing on social media

Should look something like this: `<meta name="image" property="og:image" item-prop="image" content="https://img.ascendmedia.com/files/base/ascend/hh/image/2023/02/Whinney_Christopher.63f6732fc5414.png?auto=format%2Ccompress&amp;fit=max&amp;q=70&amp;w=1200">`

**Review by zarathustra323 — CHANGES_REQUESTED** [review]
This should be moved to the core metadata component (https://github.com/parameter1/base-cms/blob/e1a636ffb2c312f48262e3ae9e503eda1ec1233f/packages/marko-web/components/page/metadata/components/common.marko#L30) and use the image width and height from GraphQL. Based on the returned dimensions, set the `og:image:width` and `og:image:height` based on what the image can support.

If the image _can_ support being that big, then the image src should be changed to handle that size. 

If the image can't be resized to their standard 1200x630, than the width and height values of the `og` tags should reflect the actual image size.

If, however, the image is too small for their standard (minimum 200 x 200), then don't add the image at all.

You'll likely need to split the `<meta>` tag into multiple entries, instead of combining `name`, `property` and `item-prop` into one meta entry like it is now. In other words, split this out into a new `<meta>`

**Comment by Shinsina** [comment]
> This should be moved to the core metadata component (https://github.com/parameter1/base-cms/blob/e1a636ffb2c312f48262e3ae9e503eda1ec1233f/packages/marko-web/components/page/metadata/components/common.marko#L30) and use the image width and height from GraphQL. Based on the returned dimensions, set the `og:image:width` and `og:image:height` based on what the image can support.
> 
> If the image _can_ support being that big, then the image src should be changed to handle that size.
> 
> If the image can't be resized to their standard 1200x630, than the width and height values of the `og` tags should reflect the actual image size.
> 
> If, however, the image is too small for their standard (minimum 200 x 200), then don't add the image at all.
> 
> You'll likely need to split the `<meta>` tag into multiple entries, instead of combining `name`, `property` and `item-prop` into one meta entry like it is now. In other words, split this out into a new `<meta>`

https://github.com/parameter1/base-cms/tree/master/packages/marko-web/components/page/metadata

Namely:
https://github.com/parameter1/base-cms/blob/master/packages/marko-web/components/page/metadata/components/common.marko
https://github.com/parameter1/base-cms/blob/master/packages/marko-web/components/page/metadata/content.marko
https://github.com/parameter1/base-cms/blob/master/packages/marko-web/components/page/metadata/website-section.marko

From what I've gathered because sections within Base itself don't have images on them (typically there are exceptions notably something like https://www.greenindustrypros.com/snowpro) . We've excluded/not been able to include image metadata for section pages, like the homepage as shown here. 

Would it make sense for cases like this to add a true `fallbackImage` on the Home section for cases like this? I noticed in https://github.com/parameter1/base-cms/blob/master/packages/marko-web/components/page/metadata/components/common.marko it's using `fallbackImage` which is coming from `config.images.fallback` (I believe, see: https://github.com/parameter1/base-cms/blob/master/packages/marko-web/config/core.js#L25). Say if a section page doesn't have an image explicitly it can still fallback to an image with dimensions provided from GraphQL and work like it does currently for content. @zarathustra323 Thoughts?

**Pull request closed without merging**
